import { Product } from "@/types/product.types";
import { Review } from "@/types/review.types";

export const reviewsData: Review[] = [
  {
    id: 1,
    user: "John Doe",
    content: "Great product! Highly recommended.",
    rating: 5,
    date: "2024-08-15",
  },
  {
    id: 2,
    user: "Jane Smith",
    content: "Good quality, but a bit pricey.",
    rating: 4,
    date: "2024-08-14",
  },
  {
    id: 3,
    user: "Peter Jones",
    content: "The product exceeded my expectations.",
    rating: 5,
    date: "2024-08-13",
  },
  {
    id: 4,
    user: "Mary Williams",
    content: "I'm satisfied with my purchase.",
    rating: 4,
    date: "2024-08-12",
  },
];

export const topSellingData: Product[] = [
  {
    id: 1,
    title: "Classic White T-Shirt",
    price: 100,
    rating: 4.5,
    srcUrl: "/images/pic1.png",
    discount: 10,
    category: "T-shirts",
    sizes: ["Small", "Medium"],
    colors: ["bg-red-600"],
    dressStyle: "Casual",
    brand: "mystyle-express",
  },
  {
    id: 2,
    title: "Blue Denim Shorts",
    price: 200,
    rating: 4.2,
    srcUrl: "/images/pic2.png",
    discount: 10,
    category: "Shorts",
    sizes: ["Large", "X-Large"],
    colors: ["bg-blue-600"],
    dressStyle: "Gym",
    brand: "mystyle-express",
  },
  {
    id: 3,
    title: "Formal White Shirt",
    price: 150,
    rating: 4.8,
    srcUrl: "/images/pic3.png",
    discount: 10,
    category: "Shirts",
    sizes: ["Medium", "Large"],
    colors: ["bg-white"],
    dressStyle: "Formal",
    brand: "the-winifred",
  },
  {
    id: 4,
    title: "Black Hoodie",
    price: 250,
    rating: 4.0,
    srcUrl: "/images/pic4.png",
    discount: 10,
    category: "Hoodie",
    sizes: ["Small", "X-Large"],
    colors: ["bg-black"],
    dressStyle: "Casual",
    brand: "the-winifred",
  },
];

export const newArrivalsData: Product[] = [
  {
    id: 5,
    title: "Blue Jeans",
    price: 120,
    rating: 4.6,
    srcUrl: "/images/pic5.png",
    discount: 10,
    category: "Jeans",
    sizes: ["Medium", "Large"],
    colors: ["bg-blue-600"],
    dressStyle: "Casual",
    timeline: "new",
    brand: "new-arrivals",
  },
  {
    id: 6,
    title: "Green T-Shirt",
    price: 220,
    rating: 4.3,
    srcUrl: "/images/pic6.png",
    discount: 10,
    category: "T-shirts",
    sizes: ["Small", "Large"],
    colors: ["bg-green-600"],
    dressStyle: "Casual",
    timeline: "new",
    brand: "new-arrivals",
  },
  {
    id: 7,
    title: "Yellow Shorts",
    price: 180,
    rating: 4.9,
    srcUrl: "/images/pic7.png",
    discount: 10,
    category: "Shorts",
    sizes: ["Medium", "X-Large"],
    colors: ["bg-yellow-300"],
    dressStyle: "Gym",
    timeline: "new",
    brand: "new-arrivals",
  },
  {
    id: 8,
    title: "Pink Party Dress",
    price: 280,
    rating: 4.1,
    srcUrl: "/images/pic8.png",
    discount: 10,
    category: "Shirts",
    sizes: ["Small", "Medium"],
    colors: ["bg-pink-600"],
    dressStyle: "Party",
    timeline: "new",
    brand: "new-arrivals",
  },
];

export const relatedProductData: Product[] = [
  {
    id: 9,
    title: "Purple Hoodie",
    price: 130,
    rating: 4.7,
    srcUrl: "/images/pic9.png",
    discount: 13,
    category: "Hoodie",
    sizes: ["Large", "X-Large"],
    colors: ["bg-purple-600"],
    dressStyle: "Casual",
    brand: "mystyle-express",
  },
  {
    id: 10,
    title: "Cyan Jeans",
    price: 230,
    rating: 4.4,
    srcUrl: "/images/pic10.png",
    discount:10,
    category: "Jeans",
    sizes: ["Small", "Medium"],
    colors: ["bg-cyan-400"],
    dressStyle: "Casual",
    brand: "the-winifred",
  },
  {
    id: 11,
    title: "Orange T-Shirt",
    price: 190,
    rating: 5.0,
    srcUrl: "/images/pic11.png",
    discount:10,
    category: "T-shirts",
    sizes: ["Medium", "Large"],
    colors: ["bg-orange-600"],
    dressStyle: "Casual",
    brand: "mystyle-express",
  },
  {
    id: 12,
    title: "Black Gym Shorts",
    price: 290,
    rating: 4.2,
    srcUrl: "/images/pic12.png",
    discount: 10,
    category: "Shorts",
    sizes: ["Small", "X-Large"],
    colors: ["bg-black"],
    dressStyle: "Gym",
    brand: "the-winifred",
  },
];

export const moreProductsData: Product[] = [
  {
    id: 13,
    title: "White Summer Dress",
    price: 350,
    rating: 4.7,
    srcUrl: "/images/dress-style-1.png",
    discount: 15,
    category: "Dresses",
    sizes: ["Small", "Medium", "Large"],
    colors: ["bg-white"],
    dressStyle: "Casual",
    brand: "the-winifred",
  },
  {
    id: 14,
    title: "Floral Maxi Skirt",
    price: 280,
    rating: 4.3,
    srcUrl: "/images/dress-style-2.png",
    discount: 0,
    category: "Skirts",
    sizes: ["Medium", "Large"],
    colors: ["bg-red-200", "bg-blue-200"],
    dressStyle: "Casual",
    brand: "mystyle-express",
  },
  {
    id: 15,
    title: "Men's Casual Shirt",
    price: 180,
    rating: 4.0,
    srcUrl: "/images/pic13.png",
    discount: 5,
    category: "Shirts",
    sizes: ["Small", "Medium", "Large", "X-Large"],
    colors: ["bg-gray-400", "bg-green-400"],
    dressStyle: "Casual",
    brand: "the-winifred",
  },
  {
    id: 16,
    title: "Women's Joggers",
    price: 220,
    rating: 4.6,
    srcUrl: "/images/pic14.png",
    discount: 10,
    category: "Pants",
    sizes: ["Small", "Medium", "Large"],
    colors: ["bg-black", "bg-pink-400"],
    dressStyle: "Sport",
    brand: "mystyle-express",
  },
  {
    id: 17,
    title: "Striped Polo Shirt",
    price: 160,
    rating: 4.1,
    srcUrl: "/images/pic15.png",
    discount: 0,
    category: "Shirts",
    sizes: ["Medium", "Large"],
    colors: ["bg-blue-700", "bg-white"],
    dressStyle: "Casual",
    brand: "the-winifred",
  },
  {
    id: 18,
    title: "High-Waist Jeans",
    price: 270,
    rating: 4.8,
    srcUrl: "/images/pic1.png", // Reusing image for simplicity
    discount: 20,
    category: "Jeans",
    sizes: ["Small", "Medium", "Large"],
    colors: ["bg-blue-500"],
    dressStyle: "Casual",
    brand: "mystyle-express",
  },
  {
    id: 19,
    title: "Cozy Knit Sweater",
    price: 300,
    rating: 4.5,
    srcUrl: "/images/pic2.png", // Reusing image for simplicity
    discount: 0,
    category: "Sweaters",
    sizes: ["Small", "Medium", "Large"],
    colors: ["bg-beige-300"],
    dressStyle: "Casual",
    brand: "the-winifred",
  },
  {
    id: 20,
    title: "Elegant Evening Gown",
    price: 800,
    rating: 4.9,
    srcUrl: "/images/dress-style-3.png",
    discount: 25,
    category: "Dresses",
    sizes: ["Small", "Medium"],
    colors: ["bg-black"],
    dressStyle: "Party",
    brand: "the-winifred",
  },
  {
    id: 21,
    title: "Sporty Track Jacket",
    price: 210,
    rating: 4.2,
    srcUrl: "/images/pic3.png", // Reusing image for simplicity
    discount: 0,
    category: "Jackets",
    sizes: ["Medium", "Large", "X-Large"],
    colors: ["bg-red-500", "bg-white"],
    dressStyle: "Sport",
    brand: "mystyle-express",
  },
  {
    id: 22,
    title: "Classic Trench Coat",
    price: 450,
    rating: 4.7,
    srcUrl: "/images/dress-style-4.png",
    discount: 10,
    category: "Coats",
    sizes: ["Small", "Medium", "Large"],
    colors: ["bg-khaki-600"],
    dressStyle: "Formal",
    brand: "the-winifred",
  },
  {
    id: 23,
    title: "Comfortable Leggings",
    price: 90,
    rating: 4.0,
    srcUrl: "/images/pic4.png", // Reusing image for simplicity
    discount: 0,
    category: "Pants",
    sizes: ["Small", "Medium", "Large", "X-Large"],
    colors: ["bg-black", "bg-gray-700"],
    dressStyle: "Casual",
    brand: "mystyle-express",
  },
  {
    id: 24,
    title: "Vintage Denim Jacket",
    price: 320,
    rating: 4.4,
    srcUrl: "/images/pic5.png", // Reusing image for simplicity
    discount: 10,
    category: "Jackets",
    sizes: ["Medium", "Large"],
    colors: ["bg-blue-800"],
    dressStyle: "Casual",
    brand: "the-winifred",
  },
];

export const allProducts: Product[] = [
  ...topSellingData,
  ...newArrivalsData,
  ...relatedProductData,
  ...moreProductsData,
];
